export enum SocialLinkType {
    INSTAGRAM = 'INSTAGRAM',
    FACEBOOK = 'FACEBOOK',
    LINKEDIN = 'LINKEDIN',
    TIKTOK = 'TIKTOK',
    PINTEREST = 'PINTEREST',
    BEHANCE = 'BEHANCE',
    WEBSITE = 'WEBSITE',
}
